apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: jkrieger-e-commerce
  type: core.Directory
  children:

  - name: EKS-LAMBDA
    type: core.Directory
    children:
    ### create S3 bucket ###
    - name: jkrieger-e-commerce-lambda-bucket
      type: udm.Application
      children:
      - name: '1.0.0'
        type: udm.DeploymentPackage
        deployables:
        - name: s3-bucket-jkrieger-e-commerce-lambda
          type: aws.s3.BucketSpec
          bucketName: jkrieger-e-commerce-lambda
          region: eu-west-1
    ### upload the artifacts to S3 bucket ###
    - name: jkrieger-e-commerce-lambda-artifacts
      type: udm.Application
      children:
      - name: '1.0.0'
        type: udm.DeploymentPackage
        deployables:
        - name: jkrieger-e-commerce-lambda-artifacts
          type: aws.s3.File
          file: !file ../cloudformation/cfn-secret-provider.zip
          acl: bucket-owner-full-control
          scanPlaceholders: false
# Provision EKS cluster using Cloudformation templates
  - name: EKS-CLOUDFORMATION
    type: core.Directory
    children:
    - name: jkrieger-e-commerce-cloudformation-eks-user
      type: udm.Application
      children:
      - name: '1.0.0'
        type: udm.DeploymentPackage
        deployables:
        - name: jkrieger-e-commerce-eks-user
          type: aws.cloudformation.Template
          file: !file ../cloudformation/eks-user.yaml
          capabilities:
          - CAPABILITY_IAM
          - CAPABILITY_NAMED_IAM
          inputVariables:
            ProjectName: jkrieger-e-commerce
            UserStackName: jkrieger-e-commerce-eks-user
            S3BucketPrefix: jkrieger-e-commerce-lambda
    - name: jkrieger-e-commerce-cloudformation-eks-vpc
      type: udm.Application
      children:
      - name: '1.0.0'
        type: udm.DeploymentPackage
        deployables:
        - name: jkrieger-e-commerce-eks-vpc
          type: aws.cloudformation.Template
          file: !file ../cloudformation/eks-vpc.yaml
          capabilities:
          - CAPABILITY_IAM
          - CAPABILITY_NAMED_IAM
          inputVariables:
            ProjectName: jkrieger-e-commerce
            VPCStackName: jkrieger-e-commerce-eks-vpc
            AvailabilityZones: eu-west-1a, eu-west-1b
    - name: jkrieger-e-commerce-cloudformation-eks-master
      type: udm.Application
      children:
      - name: '1.0.0'
        type: udm.DeploymentPackage
        deployables:
        - name: jkrieger-e-commerce-eks-master
          type: aws.cloudformation.Template
          file: !file ../cloudformation/eks-master.yaml
          capabilities:
          - CAPABILITY_IAM
          - CAPABILITY_NAMED_IAM
          inputVariables:
            ProjectName: jkrieger-e-commerce
            VPCStackName: jkrieger-e-commerce-eks-vpc
    - name: jkrieger-e-commerce-cloudformation-eks-workers
      type: udm.Application
      children:
      - name: '1.0.0'
        type: udm.DeploymentPackage
        deployables:
        - name: jkrieger-e-commerce-eks-workers
          type: aws.cloudformation.Template
          file: !file ../cloudformation/eks-workers.yaml
          capabilities:
          - CAPABILITY_IAM
          - CAPABILITY_NAMED_IAM
          inputVariables:
            ProjectName: jkrieger-e-commerce
            VPCStackName: jkrieger-e-commerce-eks-vpc
            UserStackName: jkrieger-e-commerce-eks-user
            ClusterStackName: jkrieger-e-commerce-eks-master
            ClusterName: jkrieger-e-commerce-master
            NodeGroupName: jkrieger-e-commerce
    - name: jkrieger-e-commerce-k8s-configmap
      type: udm.Application
      children:
      - name: '1.0.0'
        type: udm.DeploymentPackage
        deployables:
        - name: jkrieger-e-commerce-aws-auth
          type: k8s.ResourcesFile
          file: !file ../kubernetes/aws-auth-cm.yaml
          delimiters: "## ##"

  - name: K8S
    type: core.Directory

# Provision K8s namespace
    children:
    - name: jkrieger-e-commerce-namespace
      type: udm.Application
      children:
      - name: '1.0.0'
        type: udm.DeploymentPackage
        deployables:
        - name: xl-demo
          type: k8s.NamespaceSpec
          namespaceName: 'xl-demo'