# Provision AWS EKS cluster
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- name: jkrieger-e-commerce
  type: core.Directory
  children:
  - name: aws-jkrieger-e-commerce
    type: aws.Cloud
    accesskey: !value AWSAccessKey
    accessSecret: !value AWSAccessSecret
    children:
    - name: eks-cloudformation
      type: aws.cloudformation.Stack
      region: eu-west-1
---
apiVersion: xl-deploy/v1
kind: Environments
spec:
- name: jkrieger-e-commerce
  type: core.Directory
  children:
  - name: aws-cloudformation-jkrieger-e-commerce
    type: udm.Environment
    members:
    - Infrastructure/jkrieger-e-commerce/aws-jkrieger-e-commerce
    - Infrastructure/jkrieger-e-commerce/aws-jkrieger-e-commerce/eks-cloudformation