# Provision AWS EKS cluster
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- name: juliano-micro-1
  type: core.Directory
  children:
  - name: aws-juliano-micro-1
    type: aws.Cloud
    accesskey: !value AWSAccessKey
    accessSecret: !value AWSAccessSecret
    children:
    - name: eks-cloudformation
      type: aws.cloudformation.Stack
      region: eu-west-1
---
apiVersion: xl-deploy/v1
kind: Environments
spec:
- name: juliano-micro-1
  type: core.Directory
  children:
  - name: aws-cloudformation-juliano-micro-1
    type: udm.Environment
    members:
    - Infrastructure/juliano-micro-1/aws-juliano-micro-1
    - Infrastructure/juliano-micro-1/aws-juliano-micro-1/eks-cloudformation