apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- name: aws
  type: aws.Cloud
  accesskey: !value AWSAccessKey
  accessSecret: !value AWSAccessSecret

---
apiVersion: xl-deploy/v1
kind: Environments
spec:
- name: AWS Dictionary
  type: udm.Dictionary
  entries:
    region: !value AWSRegion
- name: AWS
  type: udm.Environment
  members:
  - "~Infrastructure/aws"
  dictionaries:
  - "~Environments/AWS Dictionary"