apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: jkmonolith-2
  type: core.Directory
  children:
    - name: jkmonolith-2-app-service
      type: udm.Application
      children:
      - name: '1.0'
        type: udm.DeploymentPackage
        deployables:
        - name: jkmonolith-2-app
          type: aws.ecs.ServiceSpec
          serviceName: jkmonolith-2-app
          desiredCount: 1
          maxDrainRetryCount: 100
          launchType: FARGATE
          networkMode: awsvpc
          assignPublicIp: true
          executionRole: 'arn:aws:iam::932770550094:role/ecsTaskExecutionRole'
          cpu: 2048
          memory: 4096
          subnets:
          - 'Name:jkmonolith-2-ecs-subnet-ipv4-az-1a'
          - 'Name:jkmonolith-2-ecs-subnet-ipv4-az-1b'
          securityGroups:
          - 'Name:jkmonolith-2-ecs-security-group'
          loadBalancers:
          - name: jkmonolith-2-app-alb
            type: aws.ecs.LoadBalancerSpec
            targetGroupArn: Name:jkmonolith-2-targetgroup
            containerName: jkmonolith-2-app
            containerPort: 8080
          containerDefinitions:
          - name: jkmonolith-2-app
            containerName: jkmonolith-2-app
            type: aws.ecs.ContainerDefinitionSpec
            image: jkriegerxl/ecommerce-monolith
            cpu: 1024
            softMemoryLimit: 768
            portMappings:
            - name: port-mapping-8080
              type: aws.ecs.PortSpec
              containerPort: 8080
            logConfiguration:
            - name: cloudwatch-log-registry
              type: aws.ecs.LogConfigurationSpec
              logDriver: awslogs
              options:
                awslogs-group: "/ecs/ecommerce"
                awslogs-region: '{{region}}'
                awslogs-stream-prefix: ecs-ecommerce
            environment:
              SPRING_PROFILES_ACTIVE: prod,swagger
              SPRING_DATASOURCE_URL: jdbc:mysql://{{MYSQL_DB_ADDRESS}}:{{MYSQL_DB_PORT}}/store?useUnicode=true&characterEncoding=utf8&useSSL=false
              SPRING_DATASOURCE_USERNAME: store
              SPRING_DATASOURCE_PASSWORD: !value MySQLMasterPassword 
              # JHIPSTER_SLEEP: 10 # gives time for the database to boot before the application
              # JAVA_OPTS:  -Xmx256m -Xms256m