FROM xebialabsunsupported/xl-deploy:8.5.0

COPY default-conf/* /opt/xebialabs/xl-deploy-server/default-conf/

COPY lib/* /opt/xebialabs/xl-deploy-server/lib/

COPY plugins/* /opt/xebialabs/xl-deploy-server/plugins/